language: node_js

node_js:
    - iojs
    - "0.12"

matrix:
    allow_failures:
        - node_js: iojs

before_install: npm install -g gulp-cli
install: npm install
after_script: "npm install coveralls && cat ./lcov.info | coveralls"
